In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import statistics as st
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier as tree
from sklearn import metrics
from sklearn import svm

In [2]:
dataSet = pd.read_csv('https://pycourse.s3.amazonaws.com/banknote_authentication.txt', header=None, names=['variance', 'skewness', 'curtosis', 'entropy', 'class'])

In [3]:
#1.	Qual o tamanho desse dataset (número de linhas, número de colunas)?
dataSet

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [4]:
#y = pd.read_csv('https://pycourse.s3.amazonaws.com/banknote_authentication.txt', header=None, names=['class'])
#x = pd.read_csv('https://pycourse.s3.amazonaws.com/banknote_authentication.txt', header=None, names=['variance', 'skewness', 'curtosis', 'entropy'])
x = dataSet.values[:,0:5]
y = dataSet.values[:,4]

In [5]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.3, random_state = 1)

In [6]:
x_train

array([[ 0.74054 ,  0.36625 ,  2.1992  ,  0.48403 ,  0.      ],
       [-2.3518  , -4.8359  ,  6.6479  , -0.060358,  1.      ],
       [-0.77688 ,  0.13036 , -0.031137, -0.35389 ,  1.      ],
       ...,
       [-4.3667  ,  6.0692  ,  0.57208 , -5.4668  ,  1.      ],
       [ 2.0466  ,  2.03    ,  2.1761  , -0.083634,  0.      ],
       [-2.3147  ,  3.6668  , -0.6969  , -1.2474  ,  1.      ]])

In [7]:
y_train

array([0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 0., 1., 1., 0.

In [8]:
clf_KNN = KNeighborsClassifier(n_neighbors=5)

In [9]:
clf_KNN.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [10]:
clf_KNN.predict(x_test)

array([1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1.

In [11]:
clf_KNN.score(x_train, y_train)

1.0

In [12]:
#2.	Qual a média da coluna skewness?

dataSet['skewness'].mean()

1.9223531206393603

In [13]:
#3.	Qual a média da coluna entropy?
dataSet['entropy'].mean()

-1.191656520043731

In [14]:
#4.	Qual a mediana da coluna variance?
dataSet['variance'].median()

0.49618

In [15]:
#5.	Qual a desvio padrão da coluna curtosis?
st.stdev(dataSet['curtosis'])

4.310030090106595

In [16]:
#6.	Qual a porcentagem de exemplos do dataset são cédulas falsas (class=1)?
dataClass = dataSet['class']
qtd = dataClass[dataClass == 1].count()
print((qtd / dataClass.count())* 100)

44.460641399416915


In [17]:
#7.	Qual a acurácia do KNN no conjunto de teste?
ac = []
clf = KNeighborsClassifier()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
ac.append(accuracy_score(y_test, y_pred))
print(ac)

[0.9975728155339806]


In [23]:
#8.	Qual a acurácia da Árvore de Decisão no conjunto de teste?
clf = DecisionTreeClassifier(random_state=1)

clf.fit(x_train,y_train)
y_pre = clf.predict(x_test)

print(metrics.accuracy_score(y_test, y_pre))

1.0


In [20]:
#9.	Qual a acurácia do SVM no conjunto de teste?
clf = svm.SVC(gamma='auto',kernel='rbf', random_state=1)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred))

1.0
